const ruleConstants = {
	required: "required",
	min: "min",
	max: "max",
	mustContainUpper: "mustContainUpper",
	mustContainLower: "mustContainLower",
	mustContainSpecial: "mustContainSpecial",
	decimal: "decimal",
	upperCaseOnly: "upperCaseOnly",
	lowerCaseOnly: "lowerCaseOnly",
	mustContainDigit: "mustContainDigit",
	noWhitespace: "noWhitespace",
	mustStartWith: "mustStartWith",
	mustEndWith: "mustEndWith",
	notContain: "notContain",
	length: "length",
	exactLength: "exactLength",
	isEmail: "isEmail",
	isURL: "isURL",
	isAlphanumeric: "isAlphanumeric",
	isNumeric: "isNumeric",
	isUUID: "isUUID",
	isHexadecimal: "isHexadecimal",
	isBase64: "isBase64",
	isIn: "isIn",
	notIn: "notIn",
};

export default ruleConstants;
