const ruleConstants = {
	required: "required",
	min: "min",
	max: "max",
	mustContainUpper: "mustContainUpper",
	mustContainLower: "mustContainLower",
	mustContainSpecial: "mustContainSpecial",
	decimal: "decimal",
	upperCaseOnly: "upperCaseOnly",
	lowerCaseOnly: "lowerCaseOnly",
	mustContainDigit: "mustContainDigit",
	noWhitespace: "noWhitespace",
	mustStartWith: "mustStartWith",
	mustEndWith: "mustEndWith",
	notContain: "notContain",
	length: "length",
	exactLength: "exactLength",
	email: "email",
	URL: "URL",
	alphanumeric: "alphanumeric",
	numeric: "numeric",
	uuid: "uuid",
	hexadecimal: "hexadecimal",
	base64: "base64",
	isIn: "isIn",
	notIn: "notIn",
};

export default ruleConstants;
