type TSynergyRules = {
	required?: boolean | Function;
	min?: number | Date | Function;
	max?: number | Date | Function;
	mustContainUpper?: boolean | Function;
	mustContainLower?: boolean | Function;
	mustContainSpecial?: boolean | Function;
	decimal?: boolean | Function;
	upperCaseOnly?: boolean | Function;
	lowerCaseOnly?: boolean | Function;
	mustContainDigit?: boolean | Function;
	noWhitespace?: boolean | Function;
	mustStartWith?: string | RegExp | Function;
	mustEndWith?: string | RegExp | Function;
	notContain?: string | RegExp | Function;
	length?: number | Function;
	exactLength?: number | Function;
	isEmail?: boolean | Function;
	isURL?: boolean | Function;
	isAlphanumeric?: boolean | Function;
	isNumeric?: boolean | Function;
	isUUID?: boolean | Function;
	isHexadecimal?: boolean | Function;
	isBase64?: boolean | Function;
	isIn?: Array<string | number> | Function;
	notIn?: Array<string | number> | Function;
};
