type TSynergyRule =
	| "required"
	| "min"
	| "max"
	| "mustContainUpper"
	| "mustContainLower"
	| "mustContainSpecial"
	| "decimal"
	| "upperCaseOnly"
	| "lowerCaseOnly"
	| "mustContainDigit"
	| "noWhitespace"
	| "mustStartWith"
	| "mustEndWith"
	| "notContain"
	| "length"
	| "exactLength"
	| "email"
	| "URL"
	| "alphanumeric"
	| "numeric"
	| "uuid"
	| "hexadecimal"
	| "base64"
	| "isIn"
	| "notIn";

export default TSynergyRule;
