type TSynergyRule =
	| "required"
	| "min"
	| "max"
	| "mustContainUpper"
	| "mustContainLower"
	| "mustContainSpecial"
	| "decimal"
	| "upperCaseOnly"
	| "lowerCaseOnly"
	| "mustContainDigit"
	| "noWhitespace"
	| "mustStartWith"
	| "mustEndWith"
	| "notContain"
	| "length"
	| "exactLength"
	| "isEmail"
	| "isURL"
	| "isAlphanumeric"
	| "isNumeric"
	| "isUUID"
	| "isHexadecimal"
	| "isBase64"
	| "isIn"
	| "notIn";

export default TSynergyRule;
