import {
	required,
	mustContainUpper,
	mustContainLower,
	mustContainSpecial,
	min,
	max,
	upperCaseOnly,
	lowerCaseOnly,
	mustContainDigit,
	noWhitespace,
	mustStartWith,
	mustEndWith,
	notContain,
	exactLength,
	email,
	URL,
	alphanumeric,
	numeric,
	uuid,
	hexadecimal,
	base64,
	isIn,
	notIn,
} from "~/utils/form/validators";

export default {
	required: required,
	mustContainUpper: mustContainUpper,
	mustContainLower: mustContainLower,
	mustContainSpecial: mustContainSpecial,
	min: min,
	max: max,
	upperCaseOnly: upperCaseOnly,
	lowerCaseOnly: lowerCaseOnly,
	mustContainDigit: mustContainDigit,
	noWhitespace: noWhitespace,
	mustStartWith: mustStartWith,
	mustEndWith: mustEndWith,
	notContain: notContain,
	exactLength: exactLength,
	email: email,
	URL: URL,
	alphanumeric: alphanumeric,
	numeric: numeric,
	uuid: uuid,
	hexadecimal: hexadecimal,
	base64: base64,
	in: isIn,
	notIn: notIn,
};
